project_name: mh-z19b-exporter

env:
  - GO111MODULE=on

builds:
  - main: .
    binary: mh-z19b-exporter
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

release:
  prerelease: auto
